// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCyg8NcIIdg0YZH19dxcqiobBZ6bT2Nhg',
    appId: '1:325734599073:web:3b710eac87bf3f603ee3e0',
    messagingSenderId: '325734599073',
    projectId: 'estacionarhoy',
    authDomain: 'estacionarhoy.firebaseapp.com',
    storageBucket: 'estacionarhoy.firebasestorage.app',
    measurementId: 'G-SP0X43NHV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyfisD-p4Cx1PE858oZUwstGBgLUx_ogw',
    appId: '1:325734599073:android:7be6fb9ca9d05c7f3ee3e0',
    messagingSenderId: '325734599073',
    projectId: 'estacionarhoy',
    storageBucket: 'estacionarhoy.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCyg8NcIIdg0YZH19dxcqiobBZ6bT2Nhg',
    appId: '1:325734599073:web:7b45ebfc32c21a773ee3e0',
    messagingSenderId: '325734599073',
    projectId: 'estacionarhoy',
    authDomain: 'estacionarhoy.firebaseapp.com',
    storageBucket: 'estacionarhoy.firebasestorage.app',
    measurementId: 'G-H6623YYLLG',
  );
}
